cms/blueprints/main.py
import os

from itertools import chain

from flask import request
from flask import redirect
from flask import render_template
from flask import Blueprint

from flask.ext.security import Security
from flask.ext.security import login_required
from flask.ext.security import utils

from core.forms import (
    SupplierForm, HoneyForm, BerryForm, DeleteModelForm, ProductBatchForm,
    CustomerForm)
from core.database import db
from core import models
from cms import TEMPLATE_FOLDER


cms_blueprint = Blueprint(
    'cms_blueprint', __name__, template_folder=TEMPLATE_FOLDER)


def _get_model_from_action(action):
    if 'honey' in action:
        return models.HoneyBatch
    elif 'berries' in action:
        return models.BerryBatch
    elif 'supplier' in action:
        return models.Supplier
    else:
        raise ValueError('Invalid form action')


def _get_form_from_action(request_form):
    action = request_form['action']
    if 'delete' in action:
        return DeleteModelForm(request_form)
    elif 'honey' in action:
        return HoneyForm(request_form)
    elif 'berries' in action:
        return BerryForm(request_form)
    elif 'supplier' in action:
        return SupplierForm(request_form)
    else:
        raise ValueError('Invalid form action')


def _get_all_products():
    return [p for p in models.Product.group_and_avail(
            models.Product.name)]


@cms_blueprint.route('/', methods=['GET'])
@login_required
def index():
    ''' Show main template
    '''
    return render_template('index.html')


@cms_blueprint.route('/logout', methods=['GET'])
@login_required
def logout():
    utils.logout_user()
    return redirect('/')


@cms_blueprint.route('/suppliers', methods=['GET', 'POST'])
@login_required
def suppliers():
    if request.method == 'GET':
        form = SupplierForm()
        delete_form = DeleteModelForm()
        suppliers = [s for s in models.Supplier.all()]
        return render_template(
            'suppliers.html', suppliers=suppliers, form=form,
            delete_form=delete_form)

    # create, update, or delete supplier
    form = _get_form_from_action(request.form)
    if not form.validate():
        # TODO: show errors properly
        return "{}".format(form.errors)

    action = request.form['action']
    model = _get_model_from_action(action)

    if 'add' in action:
        # creating new one
        supplier = model(name=form.name.data,
                         company_name=form.company_name.data,
                         address=form.address.data,
                         country=form.country.data,
                         email=form.email.data,
                         phone=form.phone.data,
                         comment=form.comment.data,
                         story=form.story.data)
    else:
        try:
            supplier = model.get(model._id == form.id.data)
        except model.DoesNotExist:
            raise Exception('Not found')

        if 'delete' in action:
            supplier.delete_instance()
            return redirect('/suppliers')
        else:
            # updating existing supplier
            supplier.name = form.name.data
            supplier.company_name = form.company_name.data
            supplier.email = form.email.data
            supplier.phone = form.phone.data
            supplier.address = form.address.data
            supplier.country = form.country.data
            supplier.comment = form.comment.data
            supplier.story = form.story.data

    supplier.save()
    return redirect('/suppliers')


@cms_blueprint.route('/ingredients', methods=['GET', 'POST'])
@login_required
def ingredients():
    if request.method == 'GET':
        suppliers = [s for s in models.Supplier.all()]
        ingredient_groups = [g for g in models.IngredientGroup.all()]
        honey_batches = [h for h in models.HoneyBatch.all()]
        berry_batches = [b for b in models.BerryBatch.all()]
        honey_form = HoneyForm()
        berry_form = BerryForm()
        delete_form = DeleteModelForm()
        return render_template(
            'ingredients.html', suppliers=suppliers, honey_form=honey_form,
            berry_form=berry_form, honey_batches=honey_batches,
            berry_batches=berry_batches, delete_form=delete_form,
            ingredient_groups=ingredient_groups)

    form = _get_form_from_action(request.form)
    if not form.validate():
        # TODO: show errors properly
        return "{}".format(form.errors)

    action = request.form['action']
    model = _get_model_from_action(action)
    if form.id.data:
        try:
            batch = model.get(model._id == form.id.data)
        except model.DoesNotExist:
            # TODO: show errors properly
            return 'Invalid ID'
    else:
        batch = model()

    if 'delete' in action:
        batch.delete_instance()
        return redirect('/ingredients')

    try:
        group = models.IngredientGroup.get(
            models.IngredientGroup._id == form.group.data)
    except models.IngredientGroup.DoesNotExist:
        # TODO: show errors properly
        return 'Invalid ingredient group'

    try:
        supplier = models.Supplier.get(
            models.Supplier._id == form.supplier.data)
    except models.Supplier.DoesNotExist:
        # TODO: show errors properly
        return 'Invalid supplier'

    batch.name = form.name.data
    batch.price = form.price.data
    batch.weight = form.weight.data
    batch.purchased = form.purchased.data
    batch.expires = form.expires.data
    batch.group = group
    batch.supplier = supplier

    if form.location.data:
        batch.location = form.location.data
    if form.location_zoom.data:
        batch.location_zoom = form.location_zoom.data
    if hasattr(form, 'is_frozen') and form.is_frozen.data:
        batch.is_frozen = form.is_frozen.data
    if hasattr(form, 'dry_weight') and form.dry_weight.data:
        batch.dry_weight = form.dry_weight.data

    batch.save()
    return redirect('/ingredients')


@cms_blueprint.route('/products', methods=['GET', 'POST'])
@login_required
def products():
    batch_form = ProductBatchForm(request.form)
    components = [c for c in chain(
        models.HoneyBatch.all(), models.BerryBatch.all()) if c._id]
    component_choices = [('{}.{}'.format(c.__class__.__name__, c._id),
                         '{}, {}'.format(c.name, c.purchased)) for c in
                         components]

    if request.args and request.method == 'POST':
        # A batch sale happened
        args = set(request.args)
        if not args.issubset(models.Product.attributes()):
            # TODO: proper error handling
            return 'Invalid search terms'

        product_choices = [(str(p._id), str(p._id)) for p in
                           models.Product.find(**request.args.to_dict())]
        customer_form = CustomerForm(request.form)
        customer_form.serial.choices = product_choices
        if not customer_form.validate():
            # TODO: show errors properly
            return 'error: {}'.format(customer_form.errors)

        # check if it is an existing client
        if customer_form.client_id.data:
            # TODO: implement using client id
            return 'not implemented'
        else:
            # Check if there is a client with the same name and address
            # XXX: it looks for exact match, would be good to later implement
            # a fuzzy search algorithm
            customers = models.Customer.find(
                name=customer_form.name.data,
                address=customer_form.address.data,
                email=customer_form.email.data)
            customer_count = len(customers)
            customer = None
            if customer_count > 1:
                # TODO: handle multiple customers case
                return 'multiple customers error'
            elif customer_count == 1:
                customer = customers[0]
            elif customer_count == 0:
                # create a new customer
                customer = models.Customer(
                    name=customer_form.name.data,
                    type=customer_form.type.data,
                    address=customer_form.address.data,
                    country=customer_form.country.data,
                    email=customer_form.email.data,
                    phone=customer_form.phone.data,
                    comment=customer_form.comment.data)
                customer.save()

        products = [models.Product.get(models.Product._id == pid) for pid in
                    customer_form.serial.data]
        for p in products:
            p.available = False
            p.save()

            s = models.Sale(product=p,
                            customer=customer,
                            price=customer_form.price.data,
                            discount=customer_form.discount.data)
            s.save()

        return redirect(request.url)
    elif request.method == 'POST':
        batch_form.components.choices = component_choices

        if not batch_form.validate():
            # TODO: show errors properly
            return 'error: {}'.format(batch_form.errors)

        ingredients = []
        for chosen_component in batch_form.components.data:
            cls_name, id = chosen_component.split('.')
            try:
                cls = getattr(models, cls_name)
            except AttributeError:
                # TODO: show errors properly
                return 'Invalid component'

            try:
                component = cls.get(cls._id == id)
            except cls.DoesNotExist:
                # TODO: show errors properly
                return 'Invalid component'

            ingredients.append(component)

        for _ in range(batch_form.count.data):
            # create all the jars
            p = models.Product(
                name=batch_form.name.data,
                created=batch_form.created.data,
                expires=batch_form.expires.data,

cms/blueprints/settings.py
import os

from flask import request
from flask import redirect
from flask import render_template
from flask import Blueprint
from flask import url_for

from flask.ext.security import login_required

from core.forms import DeleteModelForm
from core.models import ProductName
from core.models import ProductGroup
from core.models import IngredientGroup
from cms.forms import ProductionSettingsForm
from cms import TEMPLATE_FOLDER


settings_blueprint = Blueprint(
    'settings_blueprint', __name__, template_folder=TEMPLATE_FOLDER)


def _get_form_from_action(request_form):
    action = request_form['action']
    if 'delete' in action:
        return DeleteModelForm(request_form)
    elif 'name' in action:
        return ProductionSettingsForm(request_form)
    elif 'group' in action:
        return ProductionSettingsForm(request_form)
    elif 'ingredient' in action:
        return ProductionSettingsForm(request_form)
    else:
        raise ValueError('Invalid form action')


@settings_blueprint.route('/help', methods=['GET'])
@login_required
def help():
    return render_template('help.html')


@settings_blueprint.route('/production', methods=['GET', 'POST'])
@login_required
def production():
    if request.method == 'GET':
        names = [t for t in ProductName.all()]
        groups = [t for t in ProductGroup.all()]
        ingredients = [t for t in IngredientGroup.all()]
        form = ProductionSettingsForm()
        return render_template('production-settings.html',
                               names=names,
                               ingredients=ingredients,
                               delete_form=DeleteModelForm(),
                               name_form=form,
                               group_form=form,
                               ingredient_form=form,
                               groups=groups)

    form = _get_form_from_action(request.form)
    if not form.validate():
        # TODO: show errors properly
        return "{}".format(form.errors)

    action = request.form['action']
    if action == 'add-name':
        name = ProductName(name=form.name.data)
        name.save()
    elif action == 'add-group':
        group = ProductGroup(name=form.name.data)
        group.save()
    elif action == 'add-ingredient':
        ingredient = IngredientGroup(name=form.name.data)
        ingredient.save()
    elif action == 'edit-group':
        try:
            group = ProductGroup.get(ProductGroup._id == form.id.data)
        except ProductGroup.DoesNotExist:
            # TODO: show errors properly
            return "Invalid group ID"
        group.name = form.name.data
        group.save()
    elif action == 'edit-name':
        try:
            name = ProductName.get(ProductName._id == form.id.data)
        except ProductName.DoesNotExist:
            # TODO: show errors properly
            return "Invalid type ID"
        name.name = form.name.data
        name.save()
    elif action == 'edit-ingredient':
        try:
            ingredient = IngredientGroup.get(
                IngredientGroup._id == form.id.data)
        except IngredientGroup.DoesNotExist:
            # TODO: show errors properly
            return "Invalid type ID"
        name.name = form.name.data
        name.save()

    return redirect(url_for('settings_blueprint.production'))

cms/templates/_layout.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %}
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}">
        <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/uikit.almost-flat.css') }}" />
        <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/jquery.tokenize.css') }}" />
        <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/components/datepicker.min.css') }}" />
        <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/components/autocomplete.almost-flat.min.css') }}" />
        <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/mellisberry.css') }}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>{% block title %}{% endblock %}</title>
        {% endblock %}
    </head>
    <body>
        {% block navigation %}
        <nav class="uk-navbar uk-navbar-attached">
            <ul class="uk-navbar-nav">
                <li><a href="/"><img class="logo" src="{{ url_for('static', filename='img/logo.png') }}" /></a></li>
                <li class="uk-parent" data-uk-dropdown>
                    <a href="">Production <i class="uk-icon-caret-down"></i></a>
                    <div class="uk-dropdown uk-dropdown-navbar">
                        <ul class="uk-nav uk-nav-navbar">
                            <li><a href="{{ url_for('cms_blueprint.suppliers') }}">Suppliers</a></li>
                            <li><a href="{{ url_for('cms_blueprint.ingredients') }}">Ingredients</a></li>
                            <li><a href="{{ url_for('cms_blueprint.products') }}">Products</a></li>
                        </ul>
                    </div>
                </li>
                <li class="uk-parent" data-uk-dropdown>
                    <a href="">Sales <i class="uk-icon-caret-down"></i></a>
                    <div class="uk-dropdown uk-dropdown-navbar">
                        <ul class="uk-nav uk-nav-navbar">
                            <li><a href="{{ url_for('cms_blueprint.customers') }}">Customers</a></li>
                            <li><a href="{{ url_for('cms_blueprint.sales') }}">Sales log</a></li>
                        </ul>
                    </div>
                </li>
                <li class="uk-parent" data-uk-dropdown>
                    <a href="">Settings <i class="uk-icon-caret-down"></i></a>
                    <div class="uk-dropdown uk-dropdown-navbar">
                        <ul class="uk-nav uk-nav-navbar">
                            <li><a href="{{ url_for('settings_blueprint.production') }}">Production</a></li>
                            <li><a href="{{ url_for('settings_blueprint.help') }}">Help</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
            <div class="uk-navbar-flip">
                <ul class="uk-navbar-nav">
                    <li><a href="{{ url_for('cms_blueprint.logout') }}">logout</a></li>
                </ul>
            </div>
        </nav>

        {% endblock %}
        {% block content %}{% endblock %}
        {% block javascript %}
        <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-2.1.4.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/uikit.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.tokenize.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/components/datepicker.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/components/autocomplete.js') }}"></script>
        {% endblock %}
    </body>
</html>

cms/templates/clients.html
{% extends "_layout.html" %}
{% block title %}Mellis Berry → Suppliers{% endblock %}
{% block content %}
<div class="uk-container uk-margin-top">
    <h1>List of clients</h1>
    <table class="uk-table uk-table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Country</th>
                <th>Jars bought</th>
                <th>Comment</th>
            </tr>
        </thead>
        <tbody>
            {% for c in clients %}
            <tr>
                <td><i class="uk-icon-{% if s.type == 'private' %}user{% else %}building{% endif %}"></i> {{ s.name }}</td>
                <td>{{ s.country }}</td>
                <td>{{ s.comment }}</td>
                <td><a href="">more <i class="uk-icon-angle-double-right"></i><a/></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

cms/templates/help.html
{% extends "_layout.html" %}
{% block title %}Mellis Berry → Help{% endblock %}
{% block content %}
<div class="uk-container uk-margin-top">
    <h1>1. How to start</h1>
    <h2>1.1. Defining groups</h2>
    <h3>1.1.1. Product names</h3>
    <p>Product name is the final name of the product, e.g. "Raspberry Honey Delight", the term that is written on a label.</p>

    <h3>1.1.2. Product groups</h3>
    <p>Product groups are used when displaying the list of products made.</p>

    <h3>1.1.3. Ingredient groups</h3>
    <p>Ingredient groups are useful for grouping ingredients of the same type. For example raspberries and blueberries can be grouped as berries, apricots and apples are fruits.</p>
</div>
{% endblock %}

cms/templates/product-batches.html
{% extends "_layout.html" %}
{% block title %}Mellis Berry → Products{% endblock %}
{% block content %}
<div class="uk-container uk-margin-top">
    <h1>Product batches</h1>
    <table class="uk-table uk-table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Avail/Total</th>
                <th>Created</th>
                <th>Expires</th>
                <th>Group</th>
                <th>Weight</th>
                <th>Components</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for p in products %}
            <tr>
                <td>{{ p.name.name }}</td>
                <td>{{ p.count }}/{{ p.total }}</td>
                <td>{{ p.created }}</td>
                <td>{{ p.expires }}</td>
                <td>{{ p.group.name }}</td>
                <td>{{ p.weight }}</td>
                <td>{{ p.components|join(', ', attribute='name') }}</td>
                <td>
                    <a href="#edit_batch{{ p._id }}" class="uk-button" data-uk-modal="{target:'#edit_batch{{ p._id }}'}">edit</a>
                    <div id="edit_batch{{ p._id }}" class="uk-modal">
                        <div class="uk-modal-dialog">
                            <div class="uk-modal-header">
                                <h3>Edit batch</h3>
                            </div>
                            <form class="uk-form uk-form-horizontal" method="post">
                                {{ form.hidden_tag() }}
                                <input type="hidden" name="id" value="{{ p._id }}" />
                                <input type="hidden" name="action" value="edit-batch" />

                                <div class="uk-form-row">
                                    <label class="uk-form-label" for="{{ form.name.id }}">{{ form.name.label.text }}</label>
                                    <input id="{{ form.name.id }}" name="{{ form.name.id }}" value="{{ p.name }}" type="text" placeholder="{{ form.name.label.text }}" />
                                </div>
                                <div class="uk-form-row">
                                    <label class="uk-form-label" for="{{ form.created.id }}">{{ form.created.label.text }}</label>
                                    <div class="uk-form-icon">
                                        <i class="uk-icon-calendar"></i>
                                        <input id="{{ form.created.id }}" name="{{ form.created.id }}" type="text" placeholder="{{ form.created.label.text }}" value="{{ p.created }}" data-uk-datepicker="{format:'YYYY-MM-DD'}" />
                                    </div>
                                </div>
                                <div class="uk-form-row">
                                    <label class="uk-form-label" for="{{ form.expires.id }}">{{ form.expires.label.text }}</label>
                                    <div class="uk-form-icon">
                                        <i class="uk-icon-calendar"></i>
                                        <input id="{{ form.expires.id }}" name="{{ form.expires.id }}" type="text" placeholder="{{ form.expires.label.text }}" value="{{ p.expires }}" data-uk-datepicker="{format:'YYYY-MM-DD'}" />
                                    </div>
                                </div>
                                <div class="uk-form-row">
                                    <label class="uk-form-label" for="{{ form.group.id }}">{{ form.group.label.text }}</label>
                                    {% if not groups %}
                                    <input type="text" value="No groups added" disabled />
                                    {% else %}
                                    <select class="uk-button uk-form-select" id="{{ form.group.id }}" name="{{ form.group.id }}" data-uk-form-select>
                                        {% for g in groups %}
                                        <option value="{{ g._id }}" {% if g.name == p.group.name %}selected{% endif %}>{{ g.name }}</option>
                                        {% endfor %}
                                    </select>
                                    {% endif %}
                                </div>
                                <div class="uk-form-row">
                                    <label class="uk-form-label" for="{{ form.weight.id }}">{{ form.weight.label.text }}</label>
                                    <input id="{{ form.weight.id }}" name="{{ form.weight.id }}" type="text" value="{{ p.weight }}" placeholder="{{ form.weight.label.text }}" />
                                </div>
                                <div class="uk-form-row">
                                    <label class="uk-form-label" for="{{ form.count.id }}">{{ form.count.label.text }}</label>
                                    <input id="{{ form.count.id }}" name="{{ form.count.id }}" type="text" value="{{ p.count }}" placeholder="{{ form.count.label.text }}" />
                                </div>
                                <div class="uk-form-row">
                                    <label class="uk-form-label" for="{{ form.components.id }}">{{ form.components.label.text }}</label>
                                    {% if not components %}
                                    <input type="text" value="No components added" disabled />
                                    {% else %}
                                    <select class="uk-button uk-form-select" id="{{ form.components.id }}" name="{{ form.components.id }}" multiple data-uk-form-select>
                                        {% for c in components %}
                                        <option value="{{ c[0] }}">{{ c[1] }}</option>
                                        {% endfor %}
                                    </select>
                                    {% endif %}
                                </div>
                                <div class="uk-modal-footer">
                                    <a href="#!" class="uk-modal-close uk-button">Cancel</a>
                                    <button type="submit" class="uk-button">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </td>
                <td><a href="{{ url_for('cms_blueprint.products') }}?name={{ p.name._id }}&created={{ p.created }}"><i class="uk-icon-angle-double-right"></i><i class="uk-icon-angle-double-right"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <br /><a href="#new-batch" class="uk-button" data-uk-modal="{target:'#new-batch'}">Add new batch</a>
    <div id="new-batch" class="uk-modal">
        <div class="uk-modal-dialog">
            <div class="uk-modal-header">
                <h3>Add new batch</h3>
            </div>

            <form class="uk-form uk-form-horizontal" method="post">
                {{ form.hidden_tag() }}
                <input type="hidden" name="action" value="add-batch" />

                <div class="uk-form-row">
                    <label class="uk-form-label" for="{{ form.name.id }}">{{ form.name.label.text }}</label>
                    {% if not names %}
                    <input type="text" value="No names added" disabled />
                    {% else %}
                    <select class="uk-button uk-form-select" id="{{ form.name.id }}" name="{{ form.name.id }}" data-uk-form-select>
                        {% for n in names %}
                        <option value="{{ n._id }}">{{ n.name }}</option>
                        {% endfor %}
                    </select>
                    {% endif %}
                </div>
                <div class="uk-form-row">
                    <label class="uk-form-label" for="{{ form.created.id }}">{{ form.created.label.text }}</label>
                    <div class="uk-form-icon">
                        <i class="uk-icon-calendar"></i>
                        <input id="{{ form.created.id }}" name="{{ form.created.id }}" type="text" placeholder="{{ form.created.label.text }}" data-uk-datepicker="{format:'YYYY-MM-DD'}" />
                    </div>
                </div>
                <div class="uk-form-row">
                    <label class="uk-form-label" for="{{ form.expires.id }}">{{ form.expires.label.text }}</label>
                    <div class="uk-form-icon">
                        <i class="uk-icon-calendar"></i>
                        <input id="{{ form.expires.id }}" name="{{ form.expires.id }}" type="text" placeholder="{{ form.expires.label.text }}" data-uk-datepicker="{format:'YYYY-MM-DD'}" />
                    </div>
                </div>
                <div class="uk-form-row">
                    <label class="uk-form-label" for="{{ form.group.id }}">{{ form.group.label.text }}</label>
                    {% if not groups %}
                    <input type="text" value="No groups added" disabled />
                    {% else %}
                    <select class="uk-button uk-form-select" id="{{ form.group.id }}" name="{{ form.group.id }}" data-uk-form-select>
                        {% for g in groups %}
                        <option value="{{ g._id }}">{{ g.name }}</option>
                        {% endfor %}
                    </select>
                    {% endif %}
                </div>
                <div class="uk-form-row">
                    <label class="uk-form-label" for="{{ form.weight.id }}">{{ form.weight.label.text }}</label>
                    <input id="{{ form.weight.id }}" name="{{ form.weight.id }}" type="text" placeholder="{{ form.weight.label.text }}" />
                </div>
                <div class="uk-form-row">
                    <label class="uk-form-label" for="{{ form.count.id }}">{{ form.count.label.text }}</label>
                    <input id="{{ form.count.id }}" name="{{ form.count.id }}" type="text" placeholder="{{ form.count.label.text }}" />
                </div>
                <div class="uk-form-row">
                    <label class="uk-form-label" for="{{ form.components.id }}">{{ form.components.label.text }}</label>
                    {% if not components %}
                    <input type="text" value="No components added" disabled />
                    {% else %}
                    <select class="uk-button uk-form-select" id="{{ form.components.id }}" name="{{ form.components.id }}" multiple data-uk-form-select>
                        {% for c in components %}
                        <option value="{{ c.__class__.__name__ }}.{{ c._id }}">{{ c.name }} ({{ c.group.name }}, {{ c.purchased }})</option>
                        {% endfor %}
                    </select>
                    {% endif %}
                </div>

                <div class="uk-modal-footer">
                    <a href="#!" class="uk-modal-close uk-button">Cancel</a>
                    <input type="submit" class="uk-button" value="Save" />
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock %}